# Generated by Django 5.2.7 on 2025-11-13 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursosdocente', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulopaciente', models.CharField(max_length=255, verbose_name='Título Paciente')),
                ('descpaciente', models.TextField(verbose_name='Descripción del Paciente')),
                ('categoriapaciente', models.CharField(max_length=100, verbose_name='Categoría Paciente')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosdocente.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreetapa', models.CharField(max_length=100, verbose_name='Nombre Etapa')),
                ('numetapa', models.IntegerField(verbose_name='Número de Etapa')),
                ('urlvideo', models.URLField(verbose_name='URL Video')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casospacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título Pregunta')),
                ('texto', models.TextField(verbose_name='Texto de la Pregunta')),
                ('tipo', models.CharField(choices=[('MULTIPLE', 'Selección Múltiple'), ('ESCRITA', 'Respuesta Escrita')], max_length=10, verbose_name='Tipo de Pregunta')),
                ('puntuacion', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('clave_respuesta_escrita', models.TextField(blank=True, help_text="Texto o palabras clave esperadas. Solo se usa si el tipo es 'Respuesta Escrita'.", null=True, verbose_name='Clave de Corrección / Palabras clave')),
                ('retroalimentacion_general', models.TextField(blank=True, help_text='Mensaje que se muestra al estudiante sin importar su respuesta.', null=True, verbose_name='Retroalimentación General')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_creadas', to='login.docente')),
                ('id_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casospacientes.etapa')),
            ],
            options={
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='OpcionMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=255, verbose_name='Texto de la Opción')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Opción Correcta')),
                ('retroalimentacion', models.TextField(blank=True, help_text='Mensaje solo para si esta opción es seleccionada.', null=True, verbose_name='Retroalimentación Específica')),
                ('pregunta', models.ForeignKey(help_text='Pregunta a la que pertenece esta opción.', limit_choices_to={'tipo': 'MULTIPLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='casospacientes.pregunta')),
            ],
            options={
                'verbose_name': 'Opción Múltiple',
                'verbose_name_plural': 'Opciones Múltiples',
                'unique_together': {('pregunta', 'texto_opcion')},
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('calificacion_obtenida', models.DecimalField(blank=True, decimal_places=2, help_text='Puntuación asignada a esta respuesta.', max_digits=5, null=True)),
                ('respuesta_texto_libre', models.TextField(blank=True, help_text='Texto escrito por el estudiante (si es tipo ESCRITA).', null=True, verbose_name='Respuesta Texto Libre')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estudiante')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casospacientes.pregunta')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, help_text='ID de la OpcionMultiple seleccionada (si es tipo MÚLTIPLE).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='casospacientes.opcionmultiple')),
            ],
        ),
    ]
