# Generated by Django 5.2.7 on 2025-11-12 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursosdocente', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombretipo', models.CharField(max_length=50, verbose_name='Tipo de Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulopaciente', models.CharField(max_length=255, verbose_name='Título Paciente')),
                ('descpaciente', models.TextField(verbose_name='Descripción del Paciente')),
                ('categoriapaciente', models.CharField(max_length=100, verbose_name='Categoría Paciente')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosdocente.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreetapa', models.CharField(max_length=100, verbose_name='Nombre Etapa')),
                ('numetapa', models.IntegerField(verbose_name='Número de Etapa')),
                ('urlvideo', models.URLField(verbose_name='URL Video')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casospacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulopregunta', models.CharField(max_length=255, verbose_name='Título Pregunta')),
                ('id_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casospacientes.etapa')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casospacientes.tipopregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_text', models.TextField(verbose_name='Respuesta (Texto)')),
                ('respuesta_bool', models.BooleanField(verbose_name='Respuesta (Alternativa)')),
                ('retroalimentacion', models.TextField(verbose_name='Retroalimentación')),
                ('is_correct', models.BooleanField(verbose_name='Es Correcta?')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casospacientes.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestaselect', models.CharField(max_length=255, verbose_name='Respuesta Seleccionada')),
                ('fechaenvio', models.DateTimeField(verbose_name='Fecha de Envío')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estudiante')),
                ('id_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casospacientes.respuesta')),
            ],
        ),
    ]
