# Generated by Django 5.2.7 on 2025-11-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casospacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='tipo_etapa',
        ),
        migrations.AddField(
            model_name='etapa',
            name='tipo_pregunta',
            field=models.CharField(choices=[('MULTIPLE', 'Selección Múltiple (Etapa 1)'), ('EXPLORACIONES', 'Exploraciones Clínicas (Etapa 2)'), ('ESCRITA', 'Respuesta Escrita (Etapa 3)')], default='MULTIPLE', max_length=20, verbose_name='Tipo de Etapa'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='urlvideo',
            field=models.URLField(verbose_name='URL Video'),
        ),
    ]
