# Generated by Django 5.2.7 on 2025-12-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casospacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Visible para estudiantes'),
        ),
    ]
