# Generated by Django 5.2.7 on 2025-12-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casospacientes', '0002_paciente_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='completo',
            field=models.BooleanField(default=False, verbose_name='Caso Terminado (3 etapas)'),
        ),
    ]
