# Generated by Django 5.2.9 on 2025-12-10 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casospacientes', '0003_paciente_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='calificacion_obtenida',
        ),
        migrations.AddField(
            model_name='registro',
            name='intentos_fallidos',
            field=models.PositiveSmallIntegerField(default=0, help_text='Contador de errores antes de acertar (para cálculo de puntaje).', verbose_name='Intentos Fallidos'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='numetapa',
            field=models.IntegerField(help_text='Ingrese un número del 1 al 3.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Número de Etapa'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.PositiveSmallIntegerField(help_text='usar 0 para lactantes (< 1 año)', validators=[django.core.validators.MaxValueValidator(110)], verbose_name='Edad (Años)'),
        ),
    ]
