# Generated by Django 5.2.7 on 2025-11-12 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=255, verbose_name='Nombre del Curso')),
                ('objetivos', models.TextField(verbose_name='Objetivos del Curso')),
                ('fechacreacion', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.docente')),
            ],
        ),
    ]
