# Generated by Django 5.2.7 on 2025-11-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursosdocente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nombrecurso'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
