# Generated by Django 5.2.9 on 2025-12-11 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursosdocente', '0001_initial'),
        ('login', '0005_alter_docente_apellido_docente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionDocenteVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_id', models.IntegerField()),
                ('fecha_vista', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.docente')),
            ],
            options={
                'verbose_name': 'Notificación Docente Vista',
                'verbose_name_plural': 'Notificaciones Docente Vistas',
                'unique_together': {('docente', 'solicitud_id')},
            },
        ),
    ]
