# Generated by Django 5.2.7 on 2025-11-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_docente', models.CharField(blank=True, max_length=150, verbose_name='Nombre Docente')),
                ('correo_docente', models.EmailField(max_length=254, unique=True, verbose_name='Email Docente')),
                ('passw_docente', models.CharField(default='123456', max_length=25, verbose_name='Contraseña Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre Estudiante')),
                ('correo_institucional', models.EmailField(max_length=254, unique=True, verbose_name='Email Estudiante')),
                ('passw_estudiante', models.CharField(default='123456', max_length=25, verbose_name='Contraseña Estudiante')),
            ],
        ),
    ]
