# Generated by Django 5.2.7 on 2025-12-02 03:00

import applications.login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_docente', models.CharField(blank=True, max_length=150, verbose_name='Nombre Docente')),
                ('correo_docente', models.EmailField(max_length=254, unique=True, validators=[applications.login.models.validar_correo_docente], verbose_name='Email Docente')),
                ('passw_docente', models.CharField(default='123456', max_length=25, verbose_name='Contraseña Docente')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['nombre_docente'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre Estudiante')),
                ('correo_institucional', models.EmailField(max_length=254, unique=True, validators=[applications.login.models.validar_correo_alumno], verbose_name='Email Estudiante')),
                ('passw_estudiante', models.CharField(default='123456', max_length=25, verbose_name='Contraseña Estudiante')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['nombre'],
            },
        ),
    ]
