# Generated by Django 5.2.7 on 2025-10-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Docente')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Email Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Estudiante')),
                ('correo_institucional', models.EmailField(max_length=254, unique=True, verbose_name='Email Estudiante')),
            ],
        ),
    ]
