# Generated by Django 5.2.7 on 2025-12-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='apellido_docente',
            field=models.CharField(blank=True, max_length=150, verbose_name='Apellido Docente'),
        ),
    ]
