# Generated by Django 5.2.7 on 2025-12-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_docente_apellido_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='last_login',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, verbose_name='Apellido Estudiante'),
        ),
    ]
