# Generated by Django 5.2.7 on 2025-12-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_docente_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
