# Generated by Django 5.2.9 on 2025-12-10 23:02

import applications.login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_docente_last_login_estudiante_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='apellido_docente',
            field=models.CharField(blank=True, max_length=150, validators=[applications.login.models.validar_solo_letras], verbose_name='Apellido Docente'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre_docente',
            field=models.CharField(blank=True, max_length=150, validators=[applications.login.models.validar_solo_letras], verbose_name='Nombre Docente'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, validators=[applications.login.models.validar_solo_letras], verbose_name='Apellido Estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, validators=[applications.login.models.validar_solo_letras], verbose_name='Nombre Estudiante'),
        ),
    ]
