# Generated by Django 5.2.7 on 2025-12-02 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casospacientes', '0001_initial'),
        ('cursosdocente', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentajeavance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de Avance')),
                ('fecha_actualizacion', models.DateTimeField(verbose_name='Fecha de Actualización')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosdocente.curso')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estudiante')),
                ('respuestas', models.ManyToManyField(blank=True, related_name='avances', to='casospacientes.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolamientos', to='cursosdocente.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolamientos', to='login.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolamientos', to='login.estudiante')),
            ],
            options={
                'verbose_name': 'Enrolamiento',
                'verbose_name_plural': 'Enrolamientos',
                'ordering': ['fecha_inscripcion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_solicitud', models.IntegerField(choices=[(2, 'Exploración Física'), (3, 'Diagnóstico')], verbose_name='Etapa a Revisar')),
                ('motivo', models.TextField(verbose_name='Motivo de revisión')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESPONDIDA', 'Respondida')], default='PENDIENTE', max_length=20)),
                ('respuesta_docente', models.TextField(blank=True, null=True, verbose_name='Retroalimentación del Docente')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosdocente.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estudiante')),
                ('exploracion_especifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casospacientes.exploracion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casospacientes.paciente')),
            ],
            options={
                'verbose_name': 'Solicitud de Revisión',
                'verbose_name_plural': 'Solicitudes de Revisión',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
