# Generated by Django 5.2.7 on 2025-11-12 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casospacientes', '0001_initial'),
        ('cursosdocente', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentajeavance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de Avance')),
                ('fecha_actualizacion', models.DateTimeField(verbose_name='Fecha de Actualización')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosdocente.curso')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estudiante')),
                ('respuestas', models.ManyToManyField(blank=True, related_name='avances', to='casospacientes.registro')),
            ],
        ),
    ]
