# Generated by Django 5.2.9 on 2025-12-11 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursosestudiante', '0001_initial'),
        ('login', '0005_alter_docente_apellido_docente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('referencia_id', models.IntegerField()),
                ('fecha_vista', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estudiante')),
            ],
            options={
                'verbose_name': 'Notificación Vista',
                'verbose_name_plural': 'Notificaciones Vistas',
                'unique_together': {('estudiante', 'tipo', 'referencia_id')},
            },
        ),
    ]
